services:
  app_apirepro:
    build: ApiRepro
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://db:3306/reproductor?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    depends_on:
      - db
  db:
    image: mysql:8.4.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234 
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: reproductor
