services:
  app_apirepro:
    build: ApiRepro
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://ApiR:3306/reproductor?createDatabaseIfNotExist=true&characterEncoding=UTF-8&useUnicode=true
      DB_USER_NAME: root
      DB_PASSWORD: 
    restart: always
    depends_on:
      - ApiR
    command: sh -c 'until mysql -h ApiR -u root -p"$DB_PASSWORD" -e "SELECT 1"; do echo waiting for mysql; sleep 2; done; java -jar app.jar'

  ApiR:
    image: mysql:8.4.0  # Cambié a una versión más estable
    ports:
      - "3307:3306"  # Puertos mapeados
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: reproductor
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      timeout: 10s
      retries: 10
